import { ref, computed } from 'vue'
import { defineStore } from 'pinia'
import type {
  Collection,
  CollectionCreateInput,
  CollectionUpdateInput,
  CollectionSearchResult,
  Document
} from '../types'
import { useOcrStore } from './ocr'

export const useCollectionStore = defineStore('collections', () => {
  const collections = ref<Collection[]>([])
  const currentCollection = ref<Collection | null>(null)
  const collectionDocuments = ref<Document[]>([])
  const collectionSearchResults = ref<CollectionSearchResult[]>([])
  const collectionSearchQuery = ref('')
  const isLoading = ref(false)
  const error = ref<string | null>(null)

  const MOCK_COLLECTIONS: Collection[] = [
    {
      id: 'mock-col-1',
      name: '论语全集',
      description: '儒家经典《论语》的完整合集',
      category: '儒家经典',
      documentIds: [],
      createdAt: '2025-01-15',
      updatedAt: '2025-01-20'
    }
  ]

  function loadMockCollections() {
    collections.value = [...MOCK_COLLECTIONS]
    currentCollection.value = MOCK_COLLECTIONS[0]
  }

  function _toCamelCase(obj: any): any {
    if (Array.isArray(obj)) return obj.map(_toCamelCase)
    if (obj !== null && typeof obj === 'object') {
      const result: any = {}
      for (const key of Object.keys(obj)) {
        const camelKey = key.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
        result[camelKey] = _toCamelCase(obj[key])
      }
      return result
    }
    return obj
  }

  function _toSnakeCase(obj: any): any {
    if (Array.isArray(obj)) return obj.map(_toSnakeCase)
    if (obj !== null && typeof obj === 'object') {
      const result: any = {}
      for (const key of Object.keys(obj)) {
        const snakeKey = key.replace(/[A-Z]/g, (c) => '_' + c.toLowerCase())
        result[snakeKey] = _toSnakeCase(obj[key])
      }
      return result
    }
    return obj
  }

  function _resolveCollectionDocuments(collectionId: string): Document[] {
    const ocrStore = useOcrStore()
    const col = collections.value.find(c => c.id === collectionId)
    if (!col) return []
    const fromOcrStore = ocrStore.documents.filter(d => col.documentIds.includes(d.id))
    const fromCollectionStore = collectionDocuments.value.filter(d => col.documentIds.includes(d.id))
    const mergedMap = new Map<string, Document>()
    for (const d of fromCollectionStore) mergedMap.set(d.id, d)
    for (const d of fromOcrStore) mergedMap.set(d.id, d)
    const result = Array.from(mergedMap.values())
    const orderMap = new Map(col.documentIds.map((id, i) => [id, i]))
    result.sort((a, b) => (orderMap.get(a.id) ?? 99999) - (orderMap.get(b.id) ?? 99999))
    return result
  }

  function _xmlEscape(text: string): string {
    return String(text || '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&apos;')
  }

  function _safeId(raw: string): string {
    return String(raw || '').replace(/[^a-zA-Z0-9]/g, '_').replace(/^_+|_+$/g, '')
  }

  function _buildCollectionTEI(collection: Collection, docs: Document[]): string {
    const lines: string[] = []
    lines.push('<?xml version="1.0" encoding="UTF-8"?>')
    lines.push('<TEI xmlns="http://www.tei-c.org/ns/1.0">')
    lines.push('  <teiHeader>')
    lines.push('    <fileDesc>')
    lines.push(`      <titleStmt><title>${_xmlEscape(collection.name)}</title>`)
    if (collection.description) {
      lines.push(`        <note type="description">${_xmlEscape(collection.description)}</note>`)
    }
    lines.push('      </titleStmt>')
    lines.push('      <publicationStmt><p>Generated by Ancient-Text OCR Platform</p></publicationStmt>')
    lines.push('      <sourceDesc>')
    lines.push(`        <p>Collection: ${_xmlEscape(collection.name)}; Documents: ${docs.length}</p>`)
    lines.push('      </sourceDesc>')
    lines.push('    </fileDesc>')
    if (collection.category) {
      lines.push('    <profileDesc>')
      lines.push(`      <textClass><catRef target="${_xmlEscape(collection.category)}"/></textClass>`)
      lines.push('    </profileDesc>')
    }
    lines.push('  </teiHeader>')
    lines.push('  <text>')
    lines.push('    <body>')
    const safeId = _safeId(collection.id)
    lines.push(`      <div type="collection" xml:id="col_${safeId}">`)
    lines.push(`        <head>${_xmlEscape(collection.name)}</head>`)
    if (collection.category) {
      lines.push(`        <note type="category">${_xmlEscape(collection.category)}</note>`)
    }
    lines.push(`        <note type="document-count">${docs.length}</note>`)
    for (const doc of docs) {
      const docSafeId = _safeId(doc.id)
      lines.push(`        <div type="document" xml:id="doc_${docSafeId}" n="${_xmlEscape(doc.name)}">`)
      lines.push(`          <head>${_xmlEscape(doc.name)}</head>`)
      lines.push('          <div type="textbody">')
      for (const r of doc.results) {
        const content = _xmlEscape(r.corrected || r.text)
        lines.push(
          `            <seg type="line" xml:id="seg_${docSafeId}_${_safeId(r.id)}" cert="${r.confidence.toFixed(2)}">${content}</seg>`
        )
      }
      lines.push('          </div>')
      if (doc.annotations && doc.annotations.length) {
        lines.push('          <div type="annotations">')
        for (const a of doc.annotations) {
          const annContent = _xmlEscape(a.content)
          const annLabel = _xmlEscape(a.label)
          lines.push(
            `            <note type="${_xmlEscape(a.type)}" label="${annLabel}" xml:id="ann_${docSafeId}_${_safeId(a.id)}">${annContent}</note>`
          )
        }
        lines.push('          </div>')
      }
      lines.push('        </div>')
    }
    lines.push('      </div>')
    lines.push('    </body>')
    lines.push('  </text>')
    lines.push('</TEI>')
    return lines.join('\n')
  }

  async function _syncDocToBackend(doc: Document) {
    try {
      const payload = _toSnakeCase({
        id: doc.id,
        name: doc.name,
        image_url: doc.imageUrl,
        results: doc.results.map(r => ({
          id: r.id,
          text: r.text,
          bbox: r.bbox,
          confidence: r.confidence,
          corrected: r.corrected,
        })),
        annotations: (doc.annotations || []).map(a => ({
          id: a.id,
          type: a.type,
          bbox: a.bbox,
          label: a.label,
          content: a.content,
        })),
        created_at: doc.createdAt,
      })
      await fetch('/api/collections/documents/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })
    } catch (_) {
      // ignore
    }
  }

  async function fetchCollections(category?: string) {
    isLoading.value = true
    error.value = null
    try {
      const params = category ? `?category=${encodeURIComponent(category)}` : ''
      const resp = await fetch(`/api/collections${params}`)
      if (resp.ok) {
        const data = await resp.json()
        collections.value = _toCamelCase(data)
      }
    } catch (e) {
      collections.value = [...MOCK_COLLECTIONS]
    } finally {
      isLoading.value = false
    }
  }

  async function createCollection(input: CollectionCreateInput) {
    isLoading.value = true
    error.value = null
    try {
      const resp = await fetch('/api/collections', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(_toSnakeCase(input))
      })
      if (resp.ok) {
        const data = await resp.json()
        const col: Collection = _toCamelCase(data)
        collections.value.unshift(col)
        return col
      }
    } catch (e) {
      const now = new Date().toISOString()
      const col: Collection = {
        id: Date.now().toString(),
        name: input.name,
        description: input.description,
        category: input.category,
        documentIds: [],
        createdAt: now,
        updatedAt: now
      }
      collections.value.unshift(col)
      return col
    } finally {
      isLoading.value = false
    }
  }

  async function updateCollection(id: string, input: CollectionUpdateInput) {
    isLoading.value = true
    error.value = null
    try {
      const resp = await fetch(`/api/collections/${id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(_toSnakeCase(input))
      })
      if (resp.ok) {
        const data = await resp.json()
        const col: Collection = _toCamelCase(data)
        const idx = collections.value.findIndex(c => c.id === id)
        if (idx !== -1) collections.value[idx] = col
        if (currentCollection.value?.id === id) currentCollection.value = col
        return col
      }
    } catch (e) {
      const idx = collections.value.findIndex(c => c.id === id)
      if (idx !== -1) {
        collections.value[idx] = { ...collections.value[idx], ...input, updatedAt: new Date().toISOString() }
        return collections.value[idx]
      }
    } finally {
      isLoading.value = false
    }
  }

  async function deleteCollection(id: string) {
    isLoading.value = true
    error.value = null
    try {
      const resp = await fetch(`/api/collections/${id}`, { method: 'DELETE' })
      if (resp.ok) {
        collections.value = collections.value.filter(c => c.id !== id)
        if (currentCollection.value?.id === id) {
          currentCollection.value = null
          collectionDocuments.value = []
          collectionSearchResults.value = []
        }
        return true
      }
    } catch (e) {
      collections.value = collections.value.filter(c => c.id !== id)
      if (currentCollection.value?.id === id) {
        currentCollection.value = null
        collectionDocuments.value = []
        collectionSearchResults.value = []
      }
      return true
    } finally {
      isLoading.value = false
    }
    return false
  }

  async function selectCollection(id: string | null) {
    if (id === null) {
      currentCollection.value = null
      collectionDocuments.value = []
      collectionSearchResults.value = []
      return
    }
    const col = collections.value.find(c => c.id === id)
    currentCollection.value = col || null
    if (col) {
      await fetchCollectionDocuments(id)
    }
  }

  async function addDocumentToCollection(collectionId: string, document: Document | string) {
    isLoading.value = true
    const ocrStore = useOcrStore()

    let docObj: Document | null = null
    let docId: string = ''
    if (typeof document === 'string') {
      docId = document
      docObj = ocrStore.documents.find(d => d.id === document) || null
      if (!docObj && collectionDocuments.value.length) {
        docObj = collectionDocuments.value.find(d => d.id === document) || null
      }
    } else {
      docObj = document
      docId = document.id
    }

    let resultCol: Collection | null = null

    try {
      if (docObj) {
        const payload = _toSnakeCase({
          document: {
            id: docObj.id,
            name: docObj.name,
            image_url: docObj.imageUrl,
            results: docObj.results.map(r => ({
              id: r.id,
              text: r.text,
              bbox: r.bbox,
              confidence: r.confidence,
              corrected: r.corrected,
            })),
            annotations: (docObj.annotations || []).map(a => ({
              id: a.id,
              type: a.type,
              bbox: a.bbox,
              label: a.label,
              content: a.content,
            })),
            created_at: docObj.createdAt,
          }
        })
        const resp = await fetch(`/api/collections/${collectionId}/documents/with-data`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        })
        if (resp.ok) {
          const data = await resp.json()
          resultCol = _toCamelCase(data)
        }
      } else {
        const resp = await fetch(`/api/collections/${collectionId}/documents`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ document_id: docId })
        })
        if (resp.ok) {
          const data = await resp.json()
          resultCol = _toCamelCase(data)
        }
      }
    } catch (e) {
      // fallback offline mode
    }

    const idx = collections.value.findIndex(c => c.id === collectionId)
    if (resultCol) {
      if (idx !== -1) collections.value[idx] = resultCol
      if (currentCollection.value?.id === collectionId) currentCollection.value = resultCol
    } else {
      const col = collections.value.find(c => c.id === collectionId)
      if (col && !col.documentIds.includes(docId)) {
        col.documentIds.push(docId)
        col.updatedAt = new Date().toISOString()
      }
    }

    if (docObj && !collectionDocuments.value.find(d => d.id === docObj!.id)) {
      collectionDocuments.value.push(docObj)
    }
    await fetchCollectionDocuments(collectionId)
    isLoading.value = false

    return collections.value.find(c => c.id === collectionId) || null
  }

  async function removeDocumentFromCollection(collectionId: string, documentId: string) {
    isLoading.value = true
    try {
      const resp = await fetch(`/api/collections/${collectionId}/documents/${documentId}`, { method: 'DELETE' })
      if (resp.ok) {
        const data = await resp.json()
        const col: Collection = _toCamelCase(data)
        const idx = collections.value.findIndex(c => c.id === collectionId)
        if (idx !== -1) collections.value[idx] = col
        if (currentCollection.value?.id === collectionId) {
          currentCollection.value = col
          collectionDocuments.value = collectionDocuments.value.filter(d => d.id !== documentId)
        }
        return col
      }
    } catch (e) {
      const col = collections.value.find(c => c.id === collectionId)
      if (col) {
        col.documentIds = col.documentIds.filter(id => id !== documentId)
        col.updatedAt = new Date().toISOString()
        collectionDocuments.value = collectionDocuments.value.filter(d => d.id !== documentId)
        return col
      }
    } finally {
      isLoading.value = false
    }
  }

  async function fetchCollectionDocuments(collectionId: string) {
    isLoading.value = true
    try {
      const resp = await fetch(`/api/collections/${collectionId}/documents`)
      if (resp.ok) {
        const data = await resp.json()
        const backendDocs: Document[] = _toCamelCase(data)
        const merged = new Map<string, Document>()
        for (const d of backendDocs) merged.set(d.id, d)
        const resolved = _resolveCollectionDocuments(collectionId)
        for (const d of resolved) {
          if (!merged.has(d.id)) merged.set(d.id, d)
          else if (d.results.length >= merged.get(d.id)!.results.length) merged.set(d.id, d)
        }
        collectionDocuments.value = Array.from(merged.values())
      } else {
        collectionDocuments.value = _resolveCollectionDocuments(collectionId)
      }
    } catch (e) {
      collectionDocuments.value = _resolveCollectionDocuments(collectionId)
    } finally {
      isLoading.value = false
    }
  }

  async function searchInCollection(collectionId: string, query: string) {
    collectionSearchQuery.value = query
    if (!query) {
      collectionSearchResults.value = []
      return
    }
    isLoading.value = true
    try {
      const resp = await fetch(`/api/collections/${collectionId}/search?query=${encodeURIComponent(query)}`)
      if (resp.ok) {
        const data = await resp.json()
        const backendResults: CollectionSearchResult[] = _toCamelCase(data)
        const localDocs = _resolveCollectionDocuments(collectionId)
        const localQ = query.toLowerCase()
        const localResults: CollectionSearchResult[] = localDocs.flatMap(d =>
          d.results
            .filter(r =>
              r.text.toLowerCase().includes(localQ) ||
              (r.corrected || '').toLowerCase().includes(localQ)
            )
            .map(r => ({ documentId: d.id, documentName: d.name, result: r }))
        )
        const keyOf = (r: CollectionSearchResult) => `${r.documentId}::${r.result.id}`
        const merged = new Map<string, CollectionSearchResult>()
        for (const r of backendResults) merged.set(keyOf(r), r)
        for (const r of localResults) merged.set(keyOf(r), r)
        collectionSearchResults.value = Array.from(merged.values())
      } else {
        collectionSearchResults.value = _localSearch(collectionId, query)
      }
    } catch (e) {
      collectionSearchResults.value = _localSearch(collectionId, query)
    } finally {
      isLoading.value = false
    }
  }

  function _localSearch(collectionId: string, query: string): CollectionSearchResult[] {
    const docs = _resolveCollectionDocuments(collectionId)
    const q = query.toLowerCase()
    return docs.flatMap(d =>
      d.results
        .filter(r =>
          r.text.toLowerCase().includes(q) ||
          (r.corrected || '').toLowerCase().includes(q)
        )
        .map(r => ({ documentId: d.id, documentName: d.name, result: r }))
    )
  }

  async function exportCollectionTEI(collectionId: string, name?: string) {
    isLoading.value = true
    error.value = null
    const col = collections.value.find(c => c.id === collectionId)
    if (!col) {
      isLoading.value = false
      return false
    }
    const docs = _resolveCollectionDocuments(collectionId)

    let xml: string | null = null
    try {
      const resp = await fetch(`/api/collections/${collectionId}/export/tei`)
      if (resp.ok) {
        xml = await resp.text()
      }
    } catch (_) {
      xml = null
    }

    if (!xml || (docs.length > 0 && xml.includes('document-count">0</note>'))) {
      xml = _buildCollectionTEI(col, docs)
    }

    if (xml) {
      const blob = new Blob([xml], { type: 'application/xml' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${name || col.name || 'collection'}.xml`
      a.click()
      URL.revokeObjectURL(url)
      isLoading.value = false
      return true
    }

    isLoading.value = false
    return false
  }

  const collectionDocumentCount = computed(() => currentCollection.value?.documentIds.length || 0)

  return {
    collections,
    currentCollection,
    collectionDocuments,
    collectionSearchResults,
    collectionSearchQuery,
    isLoading,
    error,
    collectionDocumentCount,
    loadMockCollections,
    fetchCollections,
    createCollection,
    updateCollection,
    deleteCollection,
    selectCollection,
    addDocumentToCollection,
    removeDocumentFromCollection,
    fetchCollectionDocuments,
    searchInCollection,
    exportCollectionTEI,
  }
})
